---
- name: Set BPM Suite Artifact Facts
  set_fact:
    processcontrol_artifact_url: "{{ bpms_artifact_repo + '/' + processcontrol_artifact_name }}"
    processcontrol_artifact_dl_dest: "{{ '/tmp/' + processcontrol_artifact_name }}"

- name: Check that the somefile.conf exists
  stat:
    path: "/opt/eap/standalone/deployments/kie-server.war/WEB-INF/web.xml"
  register: processcontrol_stat_result

- name: Copy KIE-Server artifact
  copy:
    src: "{{ processcontrol_artifact_url }}"
    dest: "{{ processcontrol_artifact_dl_dest }}"
  when: processcontrol_stat_result.stat.exists == False

- name: Create KIE-Server Unzip Directory
  become: true
  become_user: root
  file:
    path: "{{ processcontrol_unarchive_temp_dest }}"
    owner: "{{ jboss_user }}"
    group: "{{ jboss_group }}"
    state: directory
    mode: "755"
  when: processcontrol_stat_result.stat.exists == False

# This should overlay the BPM download over EAP, intentionally overwriting some files in the process
- name: Extract KIE-Server
  unarchive:
    src: "{{ processcontrol_artifact_dl_dest }}"
    dest: "{{ processcontrol_unarchive_temp_dest }}"
    creates: "{{ processcontrol_unarchive_temp_dest }} + '/kie-server.war'"
    copy: no
    owner: "{{ jboss_user }}"
    group: "{{ jboss_group }}"
  when: processcontrol_stat_result.stat.exists == False

- name: Move KIE-Server installation
  shell: mv /tmp/rhpam/kie-server.war /opt/eap/standalone/deployments/kie-server.war
  args:
    creates: /opt/eap/standalone/deployments/kie-server.war/WEB-INF/web.xml

#- include: java_opts.yml
